In [161]:
import numpy as np
import pandas as pd

In [162]:
np.set_printoptions(precision=3, suppress=True)

# Importing the dataset

In [163]:
dataset = pd.read_csv('Data.csv')

In [164]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values

# Taking care of missing data

In [165]:
from sklearn.preprocessing import Imputer

In [166]:
imputer = Imputer(missing_values='NaN', strategy='mean', axis=0)
imputer = imputer.fit(X[:, 1:3])

In [167]:
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [168]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

# Encoding the Independent Variable

In [169]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [170]:
X[:, 0] = LabelEncoder().fit_transform(X[:, 0])

In [171]:
X = OneHotEncoder(categorical_features=[0]).fit_transform(X).toarray()

In [172]:
X

array([[     1.   ,      0.   ,      0.   ,     44.   ,  72000.   ],
       [     0.   ,      0.   ,      1.   ,     27.   ,  48000.   ],
       [     0.   ,      1.   ,      0.   ,     30.   ,  54000.   ],
       [     0.   ,      0.   ,      1.   ,     38.   ,  61000.   ],
       [     0.   ,      1.   ,      0.   ,     40.   ,  63777.778],
       [     1.   ,      0.   ,      0.   ,     35.   ,  58000.   ],
       [     0.   ,      0.   ,      1.   ,     38.778,  52000.   ],
       [     1.   ,      0.   ,      0.   ,     48.   ,  79000.   ],
       [     0.   ,      1.   ,      0.   ,     50.   ,  83000.   ],
       [     1.   ,      0.   ,      0.   ,     37.   ,  67000.   ]])

# Encoding the Dependent Variable

In [173]:
y = LabelEncoder().fit_transform(y)

In [174]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

# Splitting the dataset into the Training set and Test set

In [175]:
from sklearn.cross_validation import train_test_split

In [176]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [177]:
X_train, X_test, y_train, y_test

(array([[     0.   ,      1.   ,      0.   ,     40.   ,  63777.778],
        [     1.   ,      0.   ,      0.   ,     37.   ,  67000.   ],
        [     0.   ,      0.   ,      1.   ,     27.   ,  48000.   ],
        [     0.   ,      0.   ,      1.   ,     38.778,  52000.   ],
        [     1.   ,      0.   ,      0.   ,     48.   ,  79000.   ],
        [     0.   ,      0.   ,      1.   ,     38.   ,  61000.   ],
        [     1.   ,      0.   ,      0.   ,     44.   ,  72000.   ],
        [     1.   ,      0.   ,      0.   ,     35.   ,  58000.   ]]),
 array([[     0.,      1.,      0.,     30.,  54000.],
        [     0.,      1.,      0.,     50.,  83000.]]),
 array([1, 1, 1, 0, 1, 0, 0, 1]),
 array([0, 0]))